# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crashmanager-gui.ui'
#
# Created: Tue Apr 22 07:51:21 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1219, 564)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(9, 9, 631, 321))
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 30, 621, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_SYSTEMTBS = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_SYSTEMTBS.setObjectName("radioButton_SYSTEMTBS")
        self.gridLayout.addWidget(self.radioButton_SYSTEMTBS, 5, 1, 1, 1)
        self.radioButton_ALLDATA = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_ALLDATA.setObjectName("radioButton_ALLDATA")
        self.gridLayout.addWidget(self.radioButton_ALLDATA, 4, 0, 1, 1)
        self.radioButton_NONSYSTEMDATA = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_NONSYSTEMDATA.setObjectName("radioButton_NONSYSTEMDATA")
        self.gridLayout.addWidget(self.radioButton_NONSYSTEMDATA, 0, 0, 1, 1)
        self.radioButton_UNDODATA = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_UNDODATA.setObjectName("radioButton_UNDODATA")
        self.gridLayout.addWidget(self.radioButton_UNDODATA, 3, 0, 1, 1)
        self.radioButton_10 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_10.setEnabled(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout.addWidget(self.radioButton_10, 1, 1, 1, 1)
        self.radioButton_SYSTEMDATA = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_SYSTEMDATA.setObjectName("radioButton_SYSTEMDATA")
        self.gridLayout.addWidget(self.radioButton_SYSTEMDATA, 2, 0, 1, 1)
        self.radioButton_SPFILE = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_SPFILE.setObjectName("radioButton_SPFILE")
        self.gridLayout.addWidget(self.radioButton_SPFILE, 0, 2, 1, 1)
        self.radioButton_NONSYSTEMTBS = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_NONSYSTEMTBS.setObjectName("radioButton_NONSYSTEMTBS")
        self.gridLayout.addWidget(self.radioButton_NONSYSTEMTBS, 3, 1, 1, 1)
        self.radioButton_21 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_21.setEnabled(False)
        self.radioButton_21.setObjectName("radioButton_21")
        self.gridLayout.addWidget(self.radioButton_21, 2, 1, 1, 1)
        self.radioButton_TEMPORARYTBS = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_TEMPORARYTBS.setObjectName("radioButton_TEMPORARYTBS")
        self.gridLayout.addWidget(self.radioButton_TEMPORARYTBS, 4, 1, 1, 1)
        self.radioButton_TEMPORARYDATA = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_TEMPORARYDATA.setObjectName("radioButton_TEMPORARYDATA")
        self.gridLayout.addWidget(self.radioButton_TEMPORARYDATA, 1, 0, 1, 1)
        self.radioButton_READONLYTBS = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_READONLYTBS.setObjectName("radioButton_READONLYTBS")
        self.gridLayout.addWidget(self.radioButton_READONLYTBS, 0, 1, 1, 1)
        self.radioButton_UNDOTBS = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_UNDOTBS.setObjectName("radioButton_UNDOTBS")
        self.gridLayout.addWidget(self.radioButton_UNDOTBS, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 621, 231))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_22 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_22.setObjectName("radioButton_22")
        self.gridLayout_2.addWidget(self.radioButton_22, 5, 1, 1, 1)
        self.radioButton_23 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_23.setObjectName("radioButton_23")
        self.gridLayout_2.addWidget(self.radioButton_23, 4, 0, 1, 1)
        self.radioButton_24 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_24.setObjectName("radioButton_24")
        self.gridLayout_2.addWidget(self.radioButton_24, 0, 0, 1, 1)
        self.radioButton_25 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_25.setObjectName("radioButton_25")
        self.gridLayout_2.addWidget(self.radioButton_25, 3, 0, 1, 1)
        self.radioButton_26 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_26.setObjectName("radioButton_26")
        self.gridLayout_2.addWidget(self.radioButton_26, 1, 1, 1, 1)
        self.radioButton_27 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_27.setObjectName("radioButton_27")
        self.gridLayout_2.addWidget(self.radioButton_27, 2, 0, 1, 1)
        self.radioButton_28 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_28.setObjectName("radioButton_28")
        self.gridLayout_2.addWidget(self.radioButton_28, 0, 2, 1, 1)
        self.radioButton_29 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_29.setObjectName("radioButton_29")
        self.gridLayout_2.addWidget(self.radioButton_29, 3, 1, 1, 1)
        self.radioButton_30 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_30.setObjectName("radioButton_30")
        self.gridLayout_2.addWidget(self.radioButton_30, 2, 1, 1, 1)
        self.radioButton_31 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_31.setObjectName("radioButton_31")
        self.gridLayout_2.addWidget(self.radioButton_31, 4, 1, 1, 1)
        self.radioButton_32 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_32.setObjectName("radioButton_32")
        self.gridLayout_2.addWidget(self.radioButton_32, 1, 0, 1, 1)
        self.radioButton_33 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_33.setObjectName("radioButton_33")
        self.gridLayout_2.addWidget(self.radioButton_33, 0, 1, 1, 1)
        self.radioButton_34 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_34.setObjectName("radioButton_34")
        self.gridLayout_2.addWidget(self.radioButton_34, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 621, 231))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_35 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_35.setObjectName("radioButton_35")
        self.gridLayout_3.addWidget(self.radioButton_35, 5, 1, 1, 1)
        self.radioButton_36 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_36.setObjectName("radioButton_36")
        self.gridLayout_3.addWidget(self.radioButton_36, 4, 0, 1, 1)
        self.radioButton_37 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_37.setObjectName("radioButton_37")
        self.gridLayout_3.addWidget(self.radioButton_37, 0, 0, 1, 1)
        self.radioButton_38 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_38.setObjectName("radioButton_38")
        self.gridLayout_3.addWidget(self.radioButton_38, 3, 0, 1, 1)
        self.radioButton_39 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_39.setObjectName("radioButton_39")
        self.gridLayout_3.addWidget(self.radioButton_39, 1, 1, 1, 1)
        self.radioButton_40 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_40.setObjectName("radioButton_40")
        self.gridLayout_3.addWidget(self.radioButton_40, 2, 0, 1, 1)
        self.radioButton_41 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_41.setObjectName("radioButton_41")
        self.gridLayout_3.addWidget(self.radioButton_41, 0, 2, 1, 1)
        self.radioButton_42 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_42.setObjectName("radioButton_42")
        self.gridLayout_3.addWidget(self.radioButton_42, 3, 1, 1, 1)
        self.radioButton_43 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_43.setObjectName("radioButton_43")
        self.gridLayout_3.addWidget(self.radioButton_43, 2, 1, 1, 1)
        self.radioButton_44 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_44.setObjectName("radioButton_44")
        self.gridLayout_3.addWidget(self.radioButton_44, 4, 1, 1, 1)
        self.radioButton_45 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_45.setObjectName("radioButton_45")
        self.gridLayout_3.addWidget(self.radioButton_45, 1, 0, 1, 1)
        self.radioButton_46 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_46.setObjectName("radioButton_46")
        self.gridLayout_3.addWidget(self.radioButton_46, 0, 1, 1, 1)
        self.radioButton_47 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_47.setObjectName("radioButton_47")
        self.gridLayout_3.addWidget(self.radioButton_47, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.radioButton_7 = QtGui.QRadioButton(self.tab_4)
        self.radioButton_7.setGeometry(QtCore.QRect(40, 40, 147, 18))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtGui.QRadioButton(self.tab_4)
        self.radioButton_8.setGeometry(QtCore.QRect(40, 70, 171, 18))
        self.radioButton_8.setObjectName("radioButton_8")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tab_5)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 10, 670, 151))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_18 = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_18.setObjectName("radioButton_18")
        self.gridLayout_5.addWidget(self.radioButton_18, 0, 0, 1, 1)
        self.radioButton_20 = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_20.setObjectName("radioButton_20")
        self.gridLayout_5.addWidget(self.radioButton_20, 0, 1, 1, 1)
        self.radioButton_15 = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_15.setObjectName("radioButton_15")
        self.gridLayout_5.addWidget(self.radioButton_15, 1, 0, 1, 1)
        self.radioButton_17 = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_17.setObjectName("radioButton_17")
        self.gridLayout_5.addWidget(self.radioButton_17, 2, 0, 1, 1)
        self.radioButton_19 = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_19.setObjectName("radioButton_19")
        self.gridLayout_5.addWidget(self.radioButton_19, 1, 1, 1, 1)
        self.radioButton_16 = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_16.setObjectName("radioButton_16")
        self.gridLayout_5.addWidget(self.radioButton_16, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 330, 631, 137))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.textBrowser = QtGui.QTextBrowser(self.verticalLayoutWidget_3)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 470, 188, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(649, 9, 561, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textBrowser_ALERTLOG = QtGui.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser_ALERTLOG.setObjectName("textBrowser_ALERTLOG")
        self.verticalLayout.addWidget(self.textBrowser_ALERTLOG)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1219, 24))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMode = QtGui.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionComplete_Recovery = QtGui.QAction(MainWindow)
        self.actionComplete_Recovery.setObjectName("actionComplete_Recovery")
        self.actionIncomplete_Recovery = QtGui.QAction(MainWindow)
        self.actionIncomplete_Recovery.setObjectName("actionIncomplete_Recovery")
        self.actionFlashback_Recovery = QtGui.QAction(MainWindow)
        self.actionFlashback_Recovery.setObjectName("actionFlashback_Recovery")
        self.actionContent = QtGui.QAction(MainWindow)
        self.actionContent.setObjectName("actionContent")
        self.menuAbout.addAction(self.actionContent)
        self.menuAbout.addAction(self.actionAbout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuMode.addAction(self.actionComplete_Recovery)
        self.menuMode.addAction(self.actionIncomplete_Recovery)
        self.menuMode.addAction(self.actionFlashback_Recovery)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QObject.connect(self.actionComplete_Recovery, QtCore.SIGNAL("activated()"), self.tabWidget.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_SYSTEMTBS.setText(QtGui.QApplication.translate("MainWindow", "Loss of the SYSTEM tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_ALLDATA.setText(QtGui.QApplication.translate("MainWindow", "Loss of all datafiles", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_NONSYSTEMDATA.setText(QtGui.QApplication.translate("MainWindow", "Loss of a non-system datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_UNDODATA.setText(QtGui.QApplication.translate("MainWindow", "Loss of an UNDO datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_10.setText(QtGui.QApplication.translate("MainWindow", "Loss of an Index tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_SYSTEMDATA.setText(QtGui.QApplication.translate("MainWindow", "Loss of a SYSTEM datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_SPFILE.setText(QtGui.QApplication.translate("MainWindow", "Loss of the spfile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_NONSYSTEMTBS.setText(QtGui.QApplication.translate("MainWindow", "Loss of a non-system tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_21.setText(QtGui.QApplication.translate("MainWindow", "Loss of all indexes in USERS tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_TEMPORARYTBS.setText(QtGui.QApplication.translate("MainWindow", "Loss of a temporary tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_TEMPORARYDATA.setText(QtGui.QApplication.translate("MainWindow", "Loss of a temporary datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_READONLYTBS.setText(QtGui.QApplication.translate("MainWindow", "Loss of a Read-Only tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_UNDOTBS.setText(QtGui.QApplication.translate("MainWindow", "Loss of the UNDO tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Complete Recovery", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_22.setText(QtGui.QApplication.translate("MainWindow", "Loss of the SYSTEM tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_23.setText(QtGui.QApplication.translate("MainWindow", "Loss of all datafiles", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_24.setText(QtGui.QApplication.translate("MainWindow", "Loss of a non-system datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_25.setText(QtGui.QApplication.translate("MainWindow", "Loss of an UNDO datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_26.setText(QtGui.QApplication.translate("MainWindow", "Loss of an Index tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_27.setText(QtGui.QApplication.translate("MainWindow", "Loss of a SYSTEM datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_28.setText(QtGui.QApplication.translate("MainWindow", "Loss of the spfile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_29.setText(QtGui.QApplication.translate("MainWindow", "Loss of a non-system tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_30.setText(QtGui.QApplication.translate("MainWindow", "Loss of all indexes in USERS tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_31.setText(QtGui.QApplication.translate("MainWindow", "Loss of a temporary tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_32.setText(QtGui.QApplication.translate("MainWindow", "Loss of a temporary datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_33.setText(QtGui.QApplication.translate("MainWindow", "Loss of a Read-Only tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_34.setText(QtGui.QApplication.translate("MainWindow", "Loss of the UNDO tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Incomplete Recovery", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_35.setText(QtGui.QApplication.translate("MainWindow", "Loss of the SYSTEM tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_36.setText(QtGui.QApplication.translate("MainWindow", "Loss of all datafiles", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_37.setText(QtGui.QApplication.translate("MainWindow", "Loss of a non-system datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_38.setText(QtGui.QApplication.translate("MainWindow", "Loss of an UNDO datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_39.setText(QtGui.QApplication.translate("MainWindow", "Loss of an Index tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_40.setText(QtGui.QApplication.translate("MainWindow", "Loss of a SYSTEM datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_41.setText(QtGui.QApplication.translate("MainWindow", "Loss of the spfile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_42.setText(QtGui.QApplication.translate("MainWindow", "Loss of a non-system tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_43.setText(QtGui.QApplication.translate("MainWindow", "Loss of all indexes in USERS tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_44.setText(QtGui.QApplication.translate("MainWindow", "Loss of a temporary tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_45.setText(QtGui.QApplication.translate("MainWindow", "Loss of a temporary datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_46.setText(QtGui.QApplication.translate("MainWindow", "Loss of a Read-Only tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_47.setText(QtGui.QApplication.translate("MainWindow", "Loss of the UNDO tablespace", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Flashback Recovery", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_7.setText(QtGui.QApplication.translate("MainWindow", "Loss of a control file", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_8.setText(QtGui.QApplication.translate("MainWindow", "Loss of all control files", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Control file", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_18.setText(QtGui.QApplication.translate("MainWindow", "Loss of a redo log file group member", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_20.setText(QtGui.QApplication.translate("MainWindow", "Loss of all redo log members of an INACTIVE group", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_15.setText(QtGui.QApplication.translate("MainWindow", "Loss of a redo log file group", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_17.setText(QtGui.QApplication.translate("MainWindow", "Loss of redo log member of a multiplexed group", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_19.setText(QtGui.QApplication.translate("MainWindow", "Loss of all redo log members of an ACTIVE group", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_16.setText(QtGui.QApplication.translate("MainWindow", "Loss of all redo log members of CURRENT group", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Redo log", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Press this button if you want to perform a crash of your instance according to the radio button selected. In this way you have to recover your instance: so be sure to have at least one useful backup of your database.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Crash it !", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Press this button if you want to have no radio button selected. In this way even if you push the &quot;Crash it !&quot; button it won\'t crash your instance.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Alert log:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMode.setTitle(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComplete_Recovery.setText(QtGui.QApplication.translate("MainWindow", "Complete Recovery", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIncomplete_Recovery.setText(QtGui.QApplication.translate("MainWindow", "Incomplete Recovery", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFlashback_Recovery.setText(QtGui.QApplication.translate("MainWindow", "Flashback Recovery", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContent.setText(QtGui.QApplication.translate("MainWindow", "Content", None, QtGui.QApplication.UnicodeUTF8))

